package edu.columbia.main.db.Models;

import java.io.Serializable;

/**
 * Created by Gideon on 2/23/15.
 */

/**
 * A POJO representing a line a log file generated by LogDB
 */
public class LogEntry implements Serializable {

    private String guid;
    private String url;
    private String fileName;

    public LogEntry(String guid, String url, String fileName) {
        this.guid = guid;
        this.url = url;
        this.fileName = fileName;
    }

    public LogEntry(String line) {

        if(line == null || line.equals(""))
            return;

        String [] parts = line.split(",");
        parts[1] = parts[1].replaceAll("url:", "");
        this.url = parts[1].trim();


        //id: 569295949648027650, url:http://twitter.com/465714163/status/569295949648027650
        if(!parts[0].contains("#"))
            this.fileName = parts[0].replaceAll("id: ","");

        //id: 569295949648027650#, url:http://twitter.com/465714163/status/56929594964802765
        else if(parts[0].indexOf("#") == parts[0].length()-1)
            this.fileName = parts[0].replaceAll("id: ","").replaceAll("#","");

        //id: -3a16ea81+0d425e8f#-163167452, url:http://ephremzlideta.blogspot.com/feeds/posts/default
        else {
            String [] idParts = parts[0].split("#");
            this.guid = idParts[0].replaceAll("id: ","").replaceAll("#","");;
            this.fileName = idParts[1];
        }

    }

    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
